### ISSUE TITLE
Constants placement may lead to wrong evaluation

### ISSUE THREAD

**Issue by Drumor** [UCL-INGI/INGInious-problems-math#3]
In an exercise, 3 answers are expected:
2xz^2e^{x^2-4y^2}
8yz^2e^{x^2-4y^2}
2ze^{x^2-4y^2}
and, for some reason, where a student answer with a different placement of constants (which have no influence on mathematical answer), the evaluation says that the answer is wrong.
Answer example :
e^{x^2-4y^2}2xz^2
-e^{x^2-4y^2}8yz^2
e^{x^2-4y^2}2z

**Comment by darkyne** [comment]
I believe your second answer example may be wrong because of the extra '-' symbol.
With the current version, I have tried the exact same example as you and moving the constant inside the multiplication does not return any error, the expressions are considered equally valid.

Do you still find any bug case related to that issue ?

**Comment by Drumor** [comment]
Was not from me but from a teacher that notify me.
If u think its ok, i close the issue.
