### ISSUE TITLE
Subscripted symbols

### ISSUE THREAD

**Issue by anthonygego** [UCL-INGI/INGInious-problems-math#5]
Subscripts are not supported in symbols, leading to this kind of parsing errors by sympy:

![Screenshot from 2021-02-25 15-50-00](https://user-images.githubusercontent.com/4233013/109620611-5dfb4500-7b3a-11eb-9c3d-1aaeec586665.png)

As this has no specific sense to sympy, two possible solutions:
- investigate if we can add pre-detectable symbols to sympy
- perform a pre-parsing with a deterministic symbol mapping. That means ``f_a`` should keep the same mapped symbol whatever the other symbols are in the expression. That could be done with a hashing function I guess.

**Comment by darkyne** [comment]
Shouldn't this be closed by https://github.com/UCL-INGI/INGInious-problems-math/pull/6 ?

I can not find any bug case where subscripted variables are not correctly handled but I'll add better unit-tests to the plugin anyway. The one I initially created are not very robust since they only test the parse_equatin aspect no the is_equal part.

**Comment by anthonygego** [comment]
You can teel github to close issues in the commit messages. Once they are merged in the master branch, they get closed.
